research_task:
  description: >
    Read the JSON data from {url} using the Filecoin JSON reader tool. Analyze the data obtained to identify 
    key trends, patterns, and performance metrics of the {topic}. Focus on turnover, profit, expenses, 
    net profit margin, and notable events.
  expected_output: >
    A structured list of key points summarizing {topic} performance, including trends, patterns, and 
    significant changes observed over the years.
  agent: researcher

reporting_task:
  description: >
    Generate a detailed and concise report of the {topic} performance in under 200 words based on the 
    analysis pointers provided by the researcher. Ensure clarity, structure, and readability while 
    summarizing business performance, trends, and key milestones.
  expected_output: >
    A well-structured and concise report documenting {topic} performance, highlighting key trends, 
    patterns, and events.
  agent: reporting_analyst

storage_task:
  description: >
    Upload the finalized report file generated by the Reporting Analyst to Filecoin using the Lighthouse 
    Storage Tool. Ensure proper metadata, accessibility, and data integrity for future retrieval. Execute the action only when the final answer is ready
  expected_output: >
    A JSON response from the Lighthouse tool containing the file's hash, size, and storage link.
  agent: database_engineer
